//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopsLLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laptop()
        {
            this.CustomerLaptops = new HashSet<CustomerLaptop>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public int DollarValue { get; set; }
        public int QuantityAvailable { get; set; }
        public int BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLaptop> CustomerLaptops { get; set; }
    }
}
